/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gezrovqgufcnbbuzymms"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlenJvdnFndWZjbmJidXp5bW1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3NDEyODcsImV4cCI6MjA4NjMxNzI4N30.LpF0npQxwb-byt0TVlhI40bVvoZLRyOwLz6cPsHsFww"
